name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  # macOS and Apple Platforms
  build-macos:
    runs-on: ${{ matrix.runner }}
    name: macOS (Swift ${{ matrix.swift-version }})
    strategy:
      matrix:
        include:
          - swift-version: 5.9
            runner: macos-14
          - swift-version: 6.1.2
            runner: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'
      - name: Install Swift ${{ matrix.swift-version }}
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Install mpg123
        run: |
          brew install mpg123
      - name: Show versions
        run: |
          xcodebuild -version
          swift --version
      - name: Clean build directory
        run: rm -rf .build
      - name: Build and Test
        run: |
          swift build -v
          swift test -v
      - name: Build Release
        run: swift build -c release -v
      - name: Run demo
        run: swift run MP3PlayerDemo --help || true

  # Code Quality (macOS only)
  code-quality:
    name: Code Quality
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install SwiftFormat
      run: |
        brew install swiftformat
        
    - name: Check SwiftFormat
      run: swiftformat --lint --config .swiftformat Sources/ Tests/
      
    - name: Format code with SwiftFormat
      run: swiftformat --config .swiftformat Sources/ Tests/

  # Package Validation
  package-validation:
    name: Package Validation
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install mpg123
      run: |
        brew install mpg123
        
    - name: Setup Swift
      uses: SwiftyLab/setup-swift@v1
      with:
        swift-version: '5.9'
        
    - name: Check package description
      run: swift package describe
      

  # Security and Dependencies
  security:
    name: Security Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  # Format Code (Manual trigger)
  format:
    name: Format Code
    runs-on: macos-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install SwiftFormat
      run: |
        brew install swiftformat
        
    - name: Format code
      run: swiftformat --config .swiftformat Sources/ Tests/
      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "style: format code with SwiftFormat"
        title: "style: format code with SwiftFormat"
        body: |
          This PR was automatically created by the CI workflow to format code with SwiftFormat.
          
          Changes:
          - Applied SwiftFormat rules to all Swift files
          - Maintained code style consistency
        branch: format-code
        delete-branch: true

  # Release job - only runs on tag pushes
  release:
    name: Create Release
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-macos, code-quality, package-validation, security]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## What's Changed
          
          This release includes:
          - MP3 decoding capabilities via mpg123
          - Swift wrapper for mpg123 C library
          - Demo CLI application for MP3 playback
          
          ## Installation
          
          ```swift
          .package(url: "https://github.com/your-username/swift-mpg123.git", from: "${{ github.ref_name }}")
          ```
          
          ## Usage
          
          ```swift
          import SwiftMpg123
          
          let decoder = MPG123()
          // ... use the decoder
          ```
        draft: false
        prerelease: false 