name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        swift: ['5.9']
        exclude:
          - os: windows-latest
            swift: '6.1.2'

    steps:
    - uses: actions/checkout@v4
    - name: Install Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v 